spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://mysql:3306/?useSSL=false&allowPublicKeyRetrieval=true
    #url: jdbc:mysql://localhost:3306/?useSSL=false&allowPublicKeyRetrieval=true

  #sql初始化，1.缺乏对使用环境的判断能力，2.当前项目中使用的mysql版本跟本地数据库使用的mysql版本存在版本差异，
  #3.springbboot集成mysql可能不能完全释放mysql在数据库能够使用的能力，以致于此处配置sql初始化时，schema.sql中的存储过程执行失败
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
      platform: mysql

  data:
    redis:
      database: 0
#      使用docker创建redis容器的时候，在redis.conf配置文件中要绑定宿主机ip跟docker的ip，如 bind 127.0.0.1 172.17.0.4
      host: redis
      #host: 127.0.0.1
#      host: 172.17.0.4
      password: 111111
#      port: 57508
      port: 6379
      timeout: 1000
      jedis:
        pool:
          enabled: true
          # 最大连接数量
          max-active: 8
          # 最大空闲连接
          max-idle: 10
          # 最大等待连接时间
          max-wait: 10000
          # 最小空闲连接
          min-idle: 0

    mongodb:
      host: mongodb
      #host: 127.0.0.1
      database: mybatis-mongodb
      username: kuan
      password: "111111"
      port: 27017
      authentication-database: admin



mybatis:
  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:mybatis-config.xml

server:
  port: 8088