services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - 3306:3306
    volumes:
      - sql_volume:/data
    networks:
      - appnet


  redis:
    build: ./redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/data
    networks:
      - appnet

  mongodb:
    #build: ./mongo
    image: 'mongo:latest'
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: kuan
      MONGO_INITDB_ROOT_PASSWORD: 111111
      MONGO_INITDB_DATABASE: mybatis-mongodb
    ports:
      - 27017:27017
    networks:
      - appnet

  app:
    build: ./app
    restart: unless-stopped
    container_name: app
    ports:
      - 8080:8088
    depends_on:
      - mysql
      - redis
      - mongodb
    networks:
      - appnet

volumes:
  sql_volume:
    external: false
  redis_volume:
    external: false

networks:
  appnet:
    driver: bridge